openapi: 3.0.0
info:
  title: Feeds API
  version: 1.0.0
  description: API documentation for feeds microservice
  x-rateLimit:
    window: 10 segundos
    maxRequests: 100
    message: Too many requests, please try again later.
servers:
  - url: /api/v1
    description: endpoint for development
  - url: /api/v1/feeds/api/v1
    description: endpoint for api gateway
paths:
  /interestFilter:
    post:
      summary: Create a new interestFilter
      tags:
        - InterestFilter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewInterestFilter'
      responses:
        '201':
          description: The created interestFilter
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: InterestFilter created successfully
                  data:
                    $ref: '#/components/schemas/InterestFilter'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottleError'
  /interestFilter/{userId}: 
    get:
      summary: Get a specific interestFilter by userId
      tags:
        - InterestFilter
      parameters:
        - in: path
          name: userId
          required: true
          description: userId of the interestFilter to get
          schema:
            type: string
      responses:
        '200':
          description: The requested interestFilter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterestFilter'
        '404':
          description: InterestFilter not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottleError'
    put:
      summary: Update an existing interestFilter by userId
      tags:
        - InterestFilter
      parameters:
        - in: path
          name: userId
          required: true
          description: userId of the interestFilter to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInterestFilter'
      responses:
        '200':
          description: The updated interestFilter
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: InterestFilter updated successfully
                  data:
                    $ref: '#/components/schemas/InterestFilter'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '404':
          description: InterestFilter not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'  
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottleError'
  /interestFilter/{id}:
    delete:
      summary: Delete an existing interestFilter by ID
      tags:
        - InterestFilter
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the interestFilter to delete
          schema:
            type: string
      responses:
        '204':
          description: InterestFilter deleted successfully
        '404':
          description: InterestFilter not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottleError'
  /itinerariesFeed:
    post:
      summary: Create a new itinerariesFeed
      tags:
        - ItinerariesFeed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewItinerariesFeed'
      responses:
        '201':
          description: The created itinerariesFeed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: ItinerariesFeed created successfully
                  data:
                    $ref: '#/components/schemas/ItinerariesFeed'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottleError'
  /itinerariesFeed/{userId}:
    get:
      summary: Get a specific itinerariesFeed by userId
      tags:
        - ItinerariesFeed
      parameters:
        - in: path
          name: userId
          required: true
          description: userId of the itinerariesFeed to get
          schema:
            type: string
      responses:
        '200':
          description: The requested itinerariesFeed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItinerariesFeed'
        '404':
          description: ItinerariesFeed not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottleError'
    put:
      summary: Update an existing itinerariesFeed by userId
      tags:
        - ItinerariesFeed
      parameters:
        - in: path
          name: userId
          required: true
          description: userId of the itinerariesFeed to update
          schema:
            type: string
      responses:
        '200':
          description: The updated itinerariesFeed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: ItinerariesFeed updated successfully
                  data:
                    $ref: '#/components/schemas/ItinerariesFeed'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '404':
          description: ItinerariesFeed not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottleError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    InterestFilter:
      type: object
      properties:
        _id:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6f9e'
        userId:
          type: string
          example: '12345abcde'
        categoryList:
          type: array
          items:
            type: string
            enum:
              - NATURE
              - CITY
              - CULTURE
              - ADVENTURE
              - RELAX
          example:
            - NATURE
            - CULTURE
      required:
        - userId
        - categoryList
    NewInterestFilter:
      type: object
      properties:
        userId:
          type: string
          example: '12345abcde'
        categoryList:
          type: array
          items:
            type: string
            enum:
              - NATURE
              - CITY
              - CULTURE
              - ADVENTURE
              - RELAX
          example:
            - CITY
            - ADVENTURE
      required:
        - userId
        - categoryList
    UpdateInterestFilter:
      type: object
      properties:
        categoryList:
          type: array
          items:
            type: string
            enum:
              - NATURE
              - CITY
              - CULTURE
              - ADVENTURE
              - RELAX
          example:
            - CITY
            - ADVENTURE
      required:
        - categoryList
    Error:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: InterestFilter not found
        appCode:
          type: string
          example: UNKNOWN_ERROR
        timestamp:
          type: string
          example: '2023-10-01T12:00:00.000Z'
    ItinerariesFeed:
      type: object
      properties:
        _id:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6f9e'
        userId:
          type: string
          example: '12345abcde'
        creationDate:
          type: string
          format: date-time
          example: '2023-10-01T12:00:00.000Z'
        itineraryList:
          type: array
          items:
            type: object
      required:
        - userId
        - creationDate
        - itineraryList
    NewItinerariesFeed:
      type: object
      properties:
        userId:
          type: string
          example: '12345abcde'
      required:
        - userId
    ThrottleError:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: Too many requests, please try again later.
        appCode:
          type: string
          example: TOO_MANY_REQUESTS
        timestamp:
          type: string
          example: '2023-10-01T12:00:00.000Z'
security:
  - bearerAuth: []