name: Generate a develop version in docker hub
on:
  pull_request: 
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  upload-to-docker-hub:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Build and push Docker image
          run: docker build -t javifdez7/horizon-feeds:develop -f Dockerfile .
          env:
            DOCKER_CLI_EXPERIMENTAL: enabled

        - name: Push Docker image to Docker Hub
          run: docker push javifdez7/horizon-feeds:develop